#############################################################
# htmlserver 
# 配置错误信息输出的连接地址，发送到用户端的可以是一个连接
# 用户直接打开连接就能看到错误信息的具体内容
#############################################################
htmlserver:
  url: "http://192.168.137.37"
  dir: "/opt/nginx/html/"
##########################################################
# post提交数据的服务器
##########################################################
apiserver:
  host: "192.168.137.37"
#############################################################
# delay 延迟设置
# batch_delay       客户端程序使用，批次延迟，等待文件更新的延迟时间，单位是秒。
#                   例如你设置的是10，客户端会等待10秒，之后再读取日志文件
#             
# foreach_delay     客户端程序使用， 当日志产生的新记录的时候，循环处理每行的时间延迟。
#                   假如，你设置的是0.2，而日志文件有10行新记录，你每处理一行
#                   都要延迟0.2秒 
#                   
# relink_to_server  客户端程序使用，如果客户端无法连接服务器端，
#                   会以这个时间间隔这个时间来重新尝试连接服务端  
# 
# log_server_check  服务端程序使用，定时检查数据库数据更新的延迟时间                  
#############################################################
delay:
  batch_delay: 1
  foreach_delay: 0
  relink_to_server: 5
  log_server_check: 2
####################################################################
# 邮件
# smtp_server_host 邮件主机地址
# smtp_server_port 邮件主机端口
####################################################################
mail:
  smtp_server_host: '127.0.0.1'
  smtp_server_port: 25
####################################################################
# 日志文件定义
# path 是监视的哪个文件
# owner 是这个文件和哪个用户关联，在web中可以显示出来。
#       格式是 用户1&用户2，至少应该有一个用户，如果没有请设置为admin
####################################################################
log_file:
  file_dest_1: 
    path: '/var/log/ceshi1.log'
    owner: 'admin&wxl'
  file_dest_2: 
    path: '/var/log/ceshi2.log'
    owner: 'admin&wyl'
  file_dest_3: 
    path: '/var/log/ceshi3.log'
    owner: 'admin&wxl&wyl'
  file_dest_4: 
    path: '/var/log/ceshi4.log'
    owner: 'admin'
  file_dest_5: 
    path: '/var/log/messages'
    owner: 'admin&wxl&wyl'
  file_dest_6: 
    path: '/var/log/secure'
    owner: 'admin&wxl&wyl'
###################################################################
# 日志发送对象是谁，这里可以指定一个字符串，后面会对接到web中，用来分区
# 谁有权限看到这个信息
###################################################################

